### ISSUE TITLE
#include "config.h" in WireCellUtil/Exceptions.h

### ISSUE THREAD

**Issue by HaiwangYu** [WireCell/wire-cell-toolkit#200]
@brettviren I believe this will cause trouble for external source code trying to `#include WireCellUtil/Exceptions.h`
https://github.com/WireCell/wire-cell-toolkit/blob/master/util/inc/WireCellUtil/Exceptions.h#L27

For example:
![Screenshot 2023-03-07 at 4 40 02 PM](https://user-images.githubusercontent.com/10383186/223559106-bb7aad32-b8a0-4313-bb83-78a87a4f5879.png)

Also I don't think we want to install this "config.h", at least not at top level, since the name is so general, right?

**Comment by brettviren** [comment]
Ah, yes this will not work as-is.

We control the `config.h` file name (in `wcb.py`) so can pick a less generic name.  I think we can also arrange to have it installed so users of WCT will pick it up.  

I'll work on this.  Mostly for my own checklist, here are my expected steps:

- [ ] update `waf-tools` to make `wcb.py` write `config.h` to a less generic name
- [ ] update `waf-tools` to install the new header
- [ ] make sure new name can be included either under `build/` where it is written and where it is installed
- [ ] update any `#include`
- [ ] port changes to `check-test` branch which moves `waf-tools` to the `waft/` subdir. (not needed for `master` but needed when that branch is merged)


Thanks for finding this mistake!

**Comment by brettviren** [comment]
Okay, i think i cleaned this up and pushed to `master`.

I added a bats test which does a simple "external" compilation to check this fix.  It won't get run automatically until we merge in #199

**Comment by HaiwangYu** [comment]
Thanks a lot! Looks like a perfect fix to me. Will test it out by building `larwirecell`.

**Comment by brettviren** [comment]
The `config.h` was still getting `#include` ed.  

This was partly missed because the old `build/config.h` was still hanging around.  When updating the code in a previous build area, one likely needs to do `wcb clean`.

A fix is inbound.
