### ISSUE TITLE
Something went wrong with noise.

### ISSUE THREAD

**Issue by brettviren** [WireCell/wire-cell-toolkit#202]
Discovered by Mike Wang (with a DNN no less!) and reported here:

  https://cdcvs.fnal.gov/redmine/issues/27898

Some regression related to noise crept in.  Haiwang finds it most plain as uncharacteristic high or low values at the very begin and end of the mean waveform.  Between v 0.20.0 and 0.23.0:

![noise1](https://user-images.githubusercontent.com/209537/227034056-7fa2ac78-dc5c-4754-90a9-79affb4ee51c.png)

Looking at the first ticks across a few versions (also from Haiwang):

![noise2](https://user-images.githubusercontent.com/209537/227034477-9f563bef-8219-4c54-9c92-35634aac35d1.png)

Something between 0.21 and 0.23 went "bad".  PR #172 is a suspect.

**Comment by HaiwangYu** [comment]
a note with more info: 
[2023-03-22 noise-debug-v2.pdf](https://github.com/WireCell/wire-cell-toolkit/files/11045671/2023-03-22.noise-debug-v2.pdf)

**Comment by brettviren** [comment]
Zooming in on the left side also shows the problem:

https://www.phy.bnl.gov/~bviren/tmp/wctsim/osd/bad-noise/bad-noise.html

Time is on the X-axis.  A ridge of high samples go down the channels.  Then there is a broader valley of low samples.

Note, each channel group samples noise from different, arbitrary wire lengths and is not meant to be a correct model for any given detector.  The data is generated via:  

https://github.com/WireCell/wire-cell-toolkit/blob/master/gen/test/test-noise-roundtrip.jsonnet

**Comment by HaiwangYu** [comment]
Yes, I saw that too on all 3 planes of the PDSP simulation.
![Screenshot 2023-03-23 at 9 23 12 AM](https://user-images.githubusercontent.com/10383186/227217494-853272dc-5750-417b-91ca-0afcdf900f32.png)

**Comment by brettviren** [comment]
Well, it seems this bug is due, at least in part, to a rather embarrassing blunder on my part!

During the refactoring of the "recycling randoms" I went through a some iteration on changing the internal API.  After that was done, I did not correctly update how that API is called when we create a recycling random generator.

https://github.com/WireCell/wire-cell-toolkit/blame/master/gen/src/AddNoise.cxx#L56

As a consequence, the "percentage replacement" value was being used to set the mean of the normal distribution.  That mean should have been set to zero but was set to 0.04.  

Changing the code to call `make_recyling()` with a proper `mean=0` and `sigma=1` arguments removes the weird high/low ends of the mean waveforms.  Because 0.04 is close to 0.0, this bug was not so obvious.

That is a real bug but even given a non-zero Gaussian mean, I do not understand the cause of the high/low ends of the mean waveform.  Something else is likely lurking.  I'll check a bit more.

**Comment by brettviren** [comment]
Here is the case when I make the mean of the "normal" distribution ridiculously large (1.0).

![inco-adc-bad](https://user-images.githubusercontent.com/209537/227339264-e9894852-73f1-4cd2-a999-c305572ba35f.png)

Note the exaggerated ends of the mean waveforms below each frame.

Here is after using proper mean of 0 for the normal distribution:

![inco-adc-good](https://user-images.githubusercontent.com/209537/227339340-6c2eefa4-0fbd-40a4-b7a4-3c7001ccaf6c.png)

The commit which is inbound provides `check_noise_roundtrip.py` to make these plots and spew some stats and `test-noise-roundtrip.bats` which will make these plots and fail the stats if they go too far out of spec again.

**Comment by HaiwangYu** [comment]
@brettviren, thanks for figuring this out so quickly. I will try it out too.

A small comment: For your test plot, is that possible to move the coordinate axises a bit away from the content (2D image and 1D waveforms)? So that the edge ticks/channels can be viewed easier.

A question: what this test plot looks like if you use mean=0.04 instead of 1? Will the the test fail in that case?

**Comment by HaiwangYu** [comment]
Hi @brettviren, seems the spectra with this fix went up a bit compared to 0.20.0 and 0.17.1.
![Screenshot 2023-03-24 at 12 10 40 PM](https://user-images.githubusercontent.com/10383186/227580811-b4ec2055-8c11-49d3-b992-9808b867e38e.png)
![Screenshot 2023-03-24 at 12 10 03 PM](https://user-images.githubusercontent.com/10383186/227580678-2b8b1a81-2405-46d9-81e3-ccdf6ccf8c20.png)

workarea:
https://www.phy.bnl.gov/~yuhw/wct-ci/gen/

gen:
```
wire-cell -l stdout -L debug -c check_pdsp_noise.jsonnet -V output=frames-9485256.tar.bz2
```

compare mean spec
```
wirecell-plot comp1d -n spec frames-0.17.1.tar.bz2 frames-9485256.tar.bz2 spec-u.pdf --chmin 0 --chmax 800 --interactive
```

**Comment by brettviren** [comment]
Thanks @HaiwangYu.  As mentioned in our chat, definitely there should be some change in the spectrum but my naive understanding is that the spectrum would become slightly lower after the bug fix.  I'll look into this more!

**Comment by HaiwangYu** [comment]
I checked that they should be loading the same noise spectra too.
![Screenshot 2023-03-24 at 3 17 05 PM](https://user-images.githubusercontent.com/10383186/227619426-1f4be423-d7eb-4f1f-894c-4f249c058134.png)

**Comment by brettviren** [comment]
@HaiwangYu thanks, I'll look at these type of plots next.

I checked kind of the same thing using the "roundtrip" test which applies this chain:

`spec->sampling->volts->adc->dac->volts->fitting->spec`

With bug fix, mean=0, output spec matches input spec up to distortions which I believe are due to inescapable ADC quantization error.

With bug added back, mean=0.04, the output spectra are slightly higher than input, beyond what quantization adds.

Adding "superbug" with mean=1.0, the fit spectra go very high.  Eg, input spectrum peak at 0.16V gives output 0f about 0.24V.

**Comment by brettviren** [comment]
I see something a little different using `comp1d`on the "roundtrip" noise.  The actual spectra are hand-made to mimic official PDSP noise but the shapes should not be exactly the same.  Also, the "roundtrip" test does not care about canonical "planes".  The channel range I plot are simply the channels getting the maximum noise in the test.

Note, I just pushed a small change to the `comp1d` plotter.  Actual changes are only cosmetic.

I'm using `EmpiricalNoiseModel` as you.  I have also looked at using `GroupNoiseModel` and observe the same "recycling bug".

I note two differences in comparing "bug" vs "no bug" pair with "roundtrip" noise related to your pair:

1. Noise from "roundtrip" test has a closer match between "bug" and "no bug".
2. It also has strong DC component missing from your noise.  This is after subtracting the median.  If instead I use the new `--baseline=mean` I get a zero value DC component.  Perhaps this is related to integer roundoff?  I note, your sample also has non-zero DC.

![test-noise-roundtrip-nobug-empno+smlbug-empno-empno-comp1d-spec0000](https://user-images.githubusercontent.com/209537/227640928-5334a9b8-1b0d-43bb-b00b-d422010938fc.png)
![test-noise-roundtrip-nobug-empno+smlbug-empno-empno-comp1d-wave0000](https://user-images.githubusercontent.com/209537/227640933-e1587424-fbc6-40c0-8d9b-b239b93e3e4d.png)

So, what's still going on?

- Something about using the concocted noise spectra in the "roundtrip" test instead of official PDSP noise spectra?

- Something about mixing signal + noise (your test) vs pure noise (my test)?

I'll audit the code between 0.23 and now.

**Comment by brettviren** [comment]
@HaiwangYu I guess something may be off about your tests?  Here is what I see with latest HEAD with your `check_pdsp_noise.jsonnet` from your web site:

![check-pdsp-noise-nobug-smlbug-comp1d-spec0000](https://user-images.githubusercontent.com/209537/227652427-c36abda1-cfcd-4fc2-ad62-959e1ab22df8.png)
![check-pdsp-noise-nobug-smlbug-comp1d-wave0000](https://user-images.githubusercontent.com/209537/227652428-20499986-cb75-456b-bef2-8778cbd174fb.png)

**Comment by HaiwangYu** [comment]
Hi @brettviren, I compared 0.20.0 and 9485256, for u plane [0, 800). And 9485256 has a higher spectra. Did you see different behavior?

**Comment by brettviren** [comment]
Okay.  I'm confused. You wrote 0.23 before.

**Comment by HaiwangYu** [comment]
If I check same channels for same configuration, I got same results as yours

![Screenshot 2023-03-24 at 6 35 15 PM](https://user-images.githubusercontent.com/10383186/227655453-b25dc5a6-0325-4ed2-aab4-67a4c8a175c2.png)

![Screenshot 2023-03-24 at 6 34 41 PM](https://user-images.githubusercontent.com/10383186/227655421-a2f27b4e-10ed-4d38-b2b6-2535bd31fbf3.png)

**Comment by brettviren** [comment]
Okay, I will look at 0.20 + bug fix compared to HEAD.

**Comment by HaiwangYu** [comment]
> Okay. I'm confused. You wrote 0.23 before.

0.23 has the same spectra as 0.20. 9485256 is also higher than 0.23.

**Comment by brettviren** [comment]
Ah, got it.  Then I'll look at 0.23! :smile:

**Comment by brettviren** [comment]
@HaiwangYu  I don't know what I'm missing.  Except for the DC frequency bin and the first/last time bins, I get good agreement between 0.23 vs HEAD and "0.04 bug" vs "no bug".

**Comment by HaiwangYu** [comment]
@brettviren, I think I found one change in PR175 may be the reason:
https://github.com/WireCell/wire-cell-toolkit/blob/c84c88b8f53c7003f889b30f3a30879f24493fba/gen/src/Digitizer.cxx#L94

- I used 0.17.1 as the **ref**: before IDFT, noise refactoring
- pr175: higher than ref
- pr175 without `round`: same as ref

![Screenshot 2023-03-24 at 8 43 43 PM](https://user-images.githubusercontent.com/10383186/227668717-b9c6d3dd-562f-4f76-ae93-1358d11e8aad.png)

I guess this is because if no explicit `round` called, some downstream code would un-explicitly use `floor`.

More in:
[2023-03-22 noise-debug-v2-digitizer.pdf](https://github.com/WireCell/wire-cell-toolkit/files/11067510/2023-03-22.noise-debug-v2-digitizer.pdf)

**Comment by brettviren** [comment]
Excellent work, @HaiwangYu !

I wish I had given more info in my commit message as I'm having a hard time remembering what exactly motivated adding `round()`.  This particular commit is in the middle of a series related to `BlobDepoFill` which is not directly related to `Digitizer`.  I must have found some problem as a side effect of the `BlobDepoFill` work.

I'd expect using `round()` would shift the ADC waveforms upward by 1/2 count on average compared to `floor()`.  We won't see this shift in the `wave` plots above due to the re-baselining `comp1d` applies.  The `spec` plot shift is in the right direction for this explanation but it is not obvious that the size of the shift is consistent with 1/2 count.

I'll spend some time to better understand the implication of `round()` compared to `floor()`.

**Comment by brettviren** [comment]
# Check `round` vs `floor` at different noise levels

I use the "roundtrip" test configured with a parameterized noise spectrum that roughly models real spectra.  For every group of 256 channels out of total 2560 channels I give progressively larger fraction of the parameterize spectrum.  Eg, first group gets `0.1x` total noise, second `0.2x`, etc.

The *nobug* label means that the original bug that spawned this issue is fixed.

## Measured mean spectra and waveform vs amount of noise

I show the measured mean spectra and waveforms for the three groups with least noise (0.1x, 0.2x and 0.3x) for the cases of directly truncating floating-point ADC values to integers (marked as `floor`) and after first applying `round()`.  Starting with the 3rd group, the higher noise groups have no substantial differences between `floor` and `round`.

## AC-coupled mean spectra

I simply set the zero-frequency bin to 0 so baseline shifts do not dominate the plot of the spectra.  No other transformation is done (besides taking mean across the group of channels).

![comp1d-floor+round-nobug-spec-ac-grp1](https://user-images.githubusercontent.com/209537/227733906-3321ab78-a648-4053-9266-d655442896e0.png)
![comp1d-floor+round-nobug-spec-ac-grp2](https://user-images.githubusercontent.com/209537/227733907-030f29a3-8bdb-428e-aaae-d44e8fd6e068.png)
![comp1d-floor+round-nobug-spec-ac-grp3](https://user-images.githubusercontent.com/209537/227733908-b861c718-c5d7-450f-8014-899ce6c29313.png)

## AC-coupled mean waveforms

The corresponding **AC-coupled waveforms** are:

![comp1d-floor+round-nobug-wave-ac-grp1](https://user-images.githubusercontent.com/209537/227734010-badf685b-2607-4d65-8c16-03b2419bc324.png)
![comp1d-floor+round-nobug-wave-ac-grp2](https://user-images.githubusercontent.com/209537/227734012-737a9aa4-f663-4bf9-a32e-e62a387d6428.png)
![comp1d-floor+round-nobug-wave-ac-grp3](https://user-images.githubusercontent.com/209537/227734015-57ddc7e0-0a35-49b8-9e98-06a5725e7a0e.png)

## DC-coupled mean waveforms

To show the baseline shift directly, the **untransformed mean waveforms** are:

![comp1d-floor+round-nobug-wave-none-grp1](https://user-images.githubusercontent.com/209537/227734257-208ab11e-06ef-4287-b01e-e8d71dd48355.png)
![comp1d-floor+round-nobug-wave-none-grp2](https://user-images.githubusercontent.com/209537/227734259-d135aaa4-7c28-4ab6-9d11-83efabb3b03a.png)
![comp1d-floor+round-nobug-wave-none-grp3](https://user-images.githubusercontent.com/209537/227734260-8282fc1a-52e2-4b29-8f00-0a4e94045534.png)

## Conclusions

- As expected, `round()` imparts a baseline shift of 1/2 ADC count compared to `floor`.  

- I think that the large distortion in group 1 spectrum for `floor` is due to more extreme **quantization error** than `round`.  I think this also explains why `floor` gives much smaller variance in the mean waveform compared to `round`.

- PDSP mean waveform has `std=0.25` compared to group 3's `std=0.04` or group 10's `std=0.12`.  Already group 3 has no `floor` vs `round` spectra difference besides baseline shift.  This leaves me with some trouble to understand why `floor` vs `round` on PDSP spectrum makes a difference.

## What do?

This really comes down to what is the **correct** vs **desired** model for ADC quantization.  Since, the answer for each may not be the same and may be a decision for each experiment, I make the application of `round()` be a configurable parameter.

But, we still should be a sensible default.  Unless people have opinions, I will make `floor` the default.

**Comment by brettviren** [comment]
# Check original bug, double sized bug and no bug

Here I look at three cases:

- **nobug** we properly use Normal distribution
- **smlbug** we use Gaussian with `mean=0.04` (original bug)
- **bigbug** we use Gaussian with `mean=0.8` 

This uses the same "roundtrip" test as above.

Here the focus is just on the case of `floor` quantization and the highest noise ("group 10").

The three mean AC-coupled waveforms:

![comp1d-floor-bugs-wave-ac-grp10](https://user-images.githubusercontent.com/209537/227739229-1490e921-1acc-4bdc-a1e8-3b5078e30f94.png)

And the three mean AC-coupled spectra:

![comp1d-floor-bugs-spec-ac-grp10](https://user-images.githubusercontent.com/209537/227739228-60b87efa-7186-4b15-8f50-90404a14a724.png)

Neither bug nor "double-bug" appears to distort the spectrum despite the damage at the ends of the waveforms.  The bug fix removes that damage.

**Comment by brettviren** [comment]
For posterity, here is a simple demonstration about the choice between `round` and `floor` in the `Digitizer`.

As a function of input voltage it shows the ADC as untruncated ``float``, `floor` or `round` at either end of the fullscale range. 

![digitizer](https://user-images.githubusercontent.com/209537/227796907-6c67f797-8e99-43eb-988a-30f097586501.png)

It is clear how `floor` is a maximally biased choice.

However, what is not shown is that we also add a `baseline` to the voltage.  This baseline could be chosen to shift the voltage by 1/2 ADC step such that `floor` would not actually be biased.  Getting this actually correct requires some careful study.  Note, in the plot, `baseline=0`.

**Comment by HaiwangYu** [comment]
Hi @brettviren, I think I made a mistake in the original `comp1d` that caused the large spectra discrepancy I saw.

The following code subtracts the median first then convert the frame to 'int16' by call `floor` in the end. This causes quite some bias and further more, bias the frame from `Digitizer::round` and `Digitizer::floor` differently.
```
frame = numpy.array((frame.T - numpy.median(frame, axis=1)).T, dtype=dtype)
```
After fixing this, or using your new `comp1d`, the spectra are consistent between `Digitizer::round` and `Digitizer::floor` except for the DC component.
![Screenshot 2023-03-26 at 8 43 54 PM](https://user-images.githubusercontent.com/10383186/227815832-7036693e-be68-4ee4-a1eb-f3f9ce3380ce.png)

I am so sorry for making this mistake.

Meanwhile, it is great that we noticed this `Digitizer::floor` to `Digitizer::round` change. Which may be just a simple baseline shift in most cases but still good to thoroughly understand its potential impact.

**Comment by HaiwangYu** [comment]
Hi @brettviren, I tried to overlay the input spectra and it seems the older version has a better consistent. My plotting script:
```python
def specs_from_file(spectra_file, planes=None, wirelen=7500, scale_factor=1.0e9):
    wire_specs = json.loads(bz2.BZ2File(spectra_file, 'r').read())
    for i, wire_spec in enumerate(wire_specs) :
        if planes is not None and wire_spec['plane'] not in planes:
            continue
        if abs(wire_spec['wirelen']-wirelen) > 10 :
            continue
        print("const {:.3e} plane {}, wirelen {:.1f}".format(wire_spec['const'],wire_spec['plane'],wire_spec['wirelen']))
        freqs = [x*1000 for x in wire_spec['freqs']]
        amps = [math.sqrt(x**2+(wire_spec['const'])**2)*scale_factor for x in wire_spec['amps']]
        return (freqs,amps)
```
and ADC -> mV scale is `4095./1400.`

![Screenshot 2023-03-27 at 11 30 47 AM](https://user-images.githubusercontent.com/10383186/227990905-3ca0327a-12f8-4058-b7a9-0431c8195a1e.png)

**Comment by brettviren** [comment]
Hi @HaiwangYu 

In the refactoring I missed the fact that the `EmpericalNoiseModel` returns a (half) spectrum with more than the number of requested samples (equal to the "fft best length").  

The `IncoherentAddNoise` was then using only the requested spectrum size portion and that effectively stretched the spectrum toward higher frequencies.  The fix now has `IncoherentAddNoise` being more tolerant.  It will perform the sampling on the overly large spectrum and then truncate the resulting waveform to fit the requested size.

I also found and fixed some problems with the handling of the white-noise "constant" that `EmpericalNoiseModel` supports.

There is still a 3% increase (0.106 -> 0.109, see last plot below) in the RMS of final waveforms compared to rel 0.20.0 and 0.21.0.  I think this is small enough that we need not delay making a release with all these fixes.  Let me know if you disagree.

See below for some diagnostic plots comparing current `HEAD` with past releases.  First the spectrum with 2 zooms at peak and bump and then the waveforms.

![comp1d-history-spec](https://user-images.githubusercontent.com/209537/228290447-d9650ef2-a446-4b76-a184-a21b005d20c1.png)
![comp1d-history-spec-zoom2](https://user-images.githubusercontent.com/209537/228290443-915a0863-2a05-428c-ac5d-11036314a1d4.png)
![comp1d-history-spec-zoom1](https://user-images.githubusercontent.com/209537/228290445-633dea95-98c0-484c-b76b-3c547aa5b628.png)
![comp1d-history-wave](https://user-images.githubusercontent.com/209537/228290450-4bc9e4f5-59eb-492e-ab6b-5e03475995e0.png)

**Comment by HaiwangYu** [comment]
Thanks @brettviren. Seems all noise related tests are OK for me. I will do some more tests and make the release.
[2023-03-28 noise-debug-v2-spctra-shift.pdf](https://github.com/WireCell/wire-cell-toolkit/files/11093601/2023-03-28.noise-debug-v2-spctra-shift.pdf)
