### ISSUE TITLE
Source node to read Trun/TC/TDC TTrees

### ISSUE THREAD

**Issue by brettviren** [WireCell/wire-cell-toolkit#297]
To enable "fine grained validation" WCT needs a way to read in ROOT trees Trun/TC/TDC and produce "live" and "dead" blob sets.

For validation, here is a bee link from WCP directly: https://www.phy.bnl.gov/twister/bee/set/6663a54d-fe88-4384-8d9d-c95439a18cf1/event/0/

- [x] Check how "dead activity maps" are produced in `MaskSlices` and mimic that for TDC reading.  Summarized in https://www.phy.bnl.gov/~bviren/wire-cell/docs/imaging-overview.html#live-dead
- [X] Implement `UbooneBlobSource` with ~up to~ **one of** 4 live or 3 dead ~merged~ blobsets.  Really, `UbooneBlobSource` should mimic `MaskSlices+GridTiling` and thus an instance should consider exactly one configuration of views (eg 3-view 2-view live or dead).  A `BlobSetMerge` can then follow just as we do with the equivalent WCT job.
- [x] rework the `uboone-blobs.jsonnet` to reflect per view instances.
- [x] construct dead slices from live slices spanned by dead blobs.
- [x] include `T_bad_ch` when it exists.
- [X] yet another rework to make `UbooneBlobSource` make its `IBlobSet` be per-slice like god (or Interfaces) intended
- [x] provide a Bee dumper of `IBlobSet` or `IBlob::vector` (and `ICluster` while we are at it)  this is needed for basic validation without having to run full clustering.
- [x] Figure out and correct time shift (see later comment below).
- [x] Validate output of `UbooneBlobSource` matches output of `BlobSetMerge` in the live and the dead branches of the `wct-uboone-img` job DFP graph.

**Comment by brettviren** [comment]
Current status:
* Development of a `UbooneBlobSource` class  to read `Trun/TC/TDC` into `IBlobSet` has started.
* A `uboone-blobs.jsonnet` configures `wire-cell` to produce `.npz` files with `IBlobSet` from `Trun/TC` ("live") or `Trun/TDC` ("dead").
* Differences in TC vs TDC loading now understood and being implemented.
* The `Trun/TC` half is/was done but refactoring is needed to better handle differences with `Trun/TDC` and that is in progress.

**Comment by brettviren** [comment]
Initial design of UbooneBlobSource provided a mapping of the two TC/TDC treach each to one of two (live/dead) IBlobSets.  This is too simple.  4+3 blobsets must be generated and ultimately merged to produce 1+1 sets.

- TC tree must be mapped two 4: 1 set of 3-live-view blobs and 3 sets of 2-live-view blobs.
- TDC tree must be mapped to 3: 3 sets of 2-dead-view blobs.

These variations can be selected from the overall TC or TDC TTree by  considering their `flag_{u,v,w}_vec` branches.

In addition to configuring for TC vs TDC "kind", configuration to enumerate the variants needs adding.  The updated UbooneBlobSource should be able to produce any number of valid variants for each kind.  This leaves open the option to expose all seven types of blobsets to the DFP graph or to effectively incorporate a BlobSetMerge so that the UbooneBlobSource acts as an "all types of live" or "etc dead" blobs.

Also, need to check and mimic how "dead activity maps" are produced in MaskSlices.

**Comment by brettviren** [comment]
The latest in `apply-pointcloud` has a `Bee` namespace in util that provides basic support for writing Bee files given point data.  Another `Bee` namespace is made in aux which uses it to convert `IBlob` into points using a standard `IBlobSampler` service.  This can be used like:

```
wire-cell \
    -A iname="file.root" -A oname="live.zip" \
    -A kind="live" root/test/uboone-blobs.jsonnet
    
bee-upload live.zip

```

That Jsonnet file is still a work in progress but to capture the main graph config, it is made like:

```
local live(iname, oname) = pg.pipeline([
    multi_source(iname, "live", ["uvw","uv","vw","wu"]),
    BeeBlobSink(oname, live_sampler),
]);
```

Comparing the Bee data from this with the one given by #298, there is at least a time shift to figure out.  But, the tracks look otherwise similar.

**Comment by brettviren** [comment]
Okay, I was simply forgetting to apply known speed and time offset in the `BlobSampler` used during Bee dumping.

Pure WCP:

https://www.phy.bnl.gov/twister/bee/set/6663a54d-fe88-4384-8d9d-c95439a18cf1/event/0/

Output of same original file as read in with `UbooneBlobSource` and no other WCT processing except sampling and writing to Bee.

https://www.phy.bnl.gov/twister/bee/set/347775c3-962e-468c-be41-feff0d45484d/event/0/

I believe that is enough of a check to call this done.  If others differ, of course, reopen with some comments.

**Comment by brettviren** [comment]
Bee display from processing file from Xin:

https://www.phy.bnl.gov/twister/bee/set/42ecc220-52ca-40bc-9c7e-c3c263df88e8/event/0/

**Comment by brettviren** [comment]
Here is the DFP graph that produced the WCT load-dump Bee.

![uboone-blobs-live](https://github.com/WireCell/wire-cell-toolkit/assets/209537/f123e0b2-c35b-4cf7-b7fa-bcfa7cb00c61)

**Comment by HaiwangYu** [comment]
Thanks @brettviren for making this! Here is my planned graph for next step:

- [ ] `UbooneBlobSource` -> `BlobSetMerge` -> `BlobClustering` -> `GlobalGeomClustering` (print out nblobs, nclusters) -> cluster file
- [ ] cluster file -> `PointTreeBuilding` -> `PointTreeBuilding` (bee dump)

ref: https://github.com/WireCell/wire-cell-toolkit/blob/apply-pointcloud/root/test/uboone-blobs.jsonnet

**Comment by HaiwangYu** [comment]
@lastgeorge , I made the above configuration and did initial tests:
WCT: c25e5003b0479158c9fd90f5f52dc906ee82d898
cfg: https://github.com/HaiwangYu/wcp-porting-img/commit/d5a6081bb128926117f27b1bc3e6c0bb92e74cc6

 initial test result:
[2024-06-24_uboone-source-val.pdf](https://github.com/user-attachments/files/15960322/2024-06-24_uboone-source-val.pdf)

**Comment by HaiwangYu** [comment]
@brettviren @lastgeorge , just updated the results from Xin. For this event, both blob and cluster number matches. Hooray!
[2024-06-24_uboone-source-val.pdf](https://github.com/user-attachments/files/15965158/2024-06-24_uboone-source-val.pdf)
