### ISSUE TITLE
hio without h5cpp

### ISSUE THREAD

**Issue by HaiwangYu** [WireCell/wire-cell-toolkit#303]
Hi @brettviren, as we talked before, `HDF5FrameTap` was used to produce training samples for DNN-ROI. Removing it due to the incompatibility of `h5cpp` is starting show impacts now.

In principle, we can replace them with `sio`, but as many infrastructure are already built on `hio`. It would be quite useful to restore the same function. I am happy to work on it. It would be even better if you give me some references, like is there an equivalent `h5::write<T>` in hdf5? Thanks!

Boundary conditions:
- only `HDF5FrameTap` is needed, 
- `HDF5FrameSource` is not needed
- it is not intended to be a general solution, but just to restore current `HDF5FrameTap` function.

**Comment by brettviren** [comment]
Thanks, @HaiwangYu  this is good to know.  I'll start on this as soon as #297 is done, which should be RSN.

BTW, this issue effectively duplicates #192 so I'll close it.  A back ink should be made so your text above can still be referenced.
