### ISSUE TITLE
as_tensor issue with CTPC

### ISSUE THREAD

**Issue by HaiwangYu** [WireCell/wire-cell-toolkit#312]
### Symptom:
After adding CTPC to Grouping [link to code](https://github.com/WireCell/wire-cell-toolkit/blob/apply-pointcloud/clus/src/PointTreeBuilding.cxx#L468-L522), `as_tensor` gives an exception
like this:
![Image](https://github.com/WireCell/wire-cell-toolkit/assets/10383186/a919f8e0-6f4f-4323-8d08-98cf85f49f9b)

### Reproducing setup:
WCT: https://github.com/WireCell/wire-cell-toolkit/commit/d2054571947b1c9a7b7505a5f836a196a768efb7
cfg: https://github.com/HaiwangYu/wcp-porting-img/commit/ebcbf18982853e0928c63abfda54c7e2273a9712

### Debug so far:
I added some cout in the TensorDMpointtree.cxx and seems the issue is related to this line:
https://github.com/WireCell/wire-cell-toolkit/blob/apply-pointcloud/aux/src/TensorDMpointtree.cxx#L108
![Image](https://github.com/WireCell/wire-cell-toolkit/assets/10383186/9b98151b-426f-419e-bec0-7c450409d4a2)

**Comment by brettviren** [comment]
Should now be fixed in `apply-pointcloud`.
