### ISSUE TITLE
zio/test_gdm fails by design

### ISSUE THREAD

**Issue by brettviren** [WireCell/wire-cell-toolkit#52]
This test needs an external domo broker+worker running in order to succeed so isn't self contained.

The best fix would be to include a C++ domo broker and C++ echo worker as actors created as part of the test.  The `test_gdp.cpp` in zio has an example.

Alternatively/temporarily, the source filename can be renamed to eg `check_gdm.cxx` which will allow it to still be built but not run as a unit test.  It can then be run manually in some way that includes also the external broker+worker.

**Comment by HaiwangYu** [comment]
It seems if I rename those tests to not to start with 'test', they would not get built with `./wcb`.

**Comment by brettviren** [comment]
Indeed!  I am mixing up support for `check_*` in zio and other waf-based projects we have going. 

I'll fix this over in WireCell/waf-tools#7

Thanks
