### ISSUE TITLE
spdlog as ups project

### ISSUE THREAD

**Issue by HaiwangYu** [WireCell/wire-cell-toolkit#71]

**Comment by HaiwangYu** [comment]
ticket:
https://cdcvs.fnal.gov/redmine/issues/24279?issue_count=1&issue_position=1

building shim repo:
https://cdcvs.fnal.gov/redmine/projects/build-framework/repository/spdlog-ssi-build

**Comment by brettviren** [comment]
Just a note, Kyle has UPS `setup spdlog v1_5_0 -q e19:prof` inside
```
docker pull fnalart/larwire:v1_00_00-e19-prof-slf7
```
aka
```
singularity pull docker://fnalart/larwire:v1_00_00-e19-prof-slf7
```

**Comment by HaiwangYu** [comment]
spdlog 1_5_0 available in larsoft v08_50_02
https://cdcvs.fnal.gov/redmine/projects/larsoft/wiki/ReleaseNotes085002
