### ISSUE TITLE
develop a `.clang-format` file

### ISSUE THREAD

**Issue by brettviren** [WireCell/wire-cell-toolkit#78]
[one under dev](https://github.com/HaiwangYu/wire-cell-toolkit/blob/clang-format/.clang-format)

**Comment by brettviren** [comment]
General consensus seems to be we put opening brace on same line for `for/if`.

Functions put opening brace on a new line (as now).

**Comment by brettviren** [comment]
Maybe `SortIncludes: false`?

https://github.com/HaiwangYu/wire-cell-toolkit/blob/clang-format/.clang-format#L75

Here's at least one case where surprises happened:

https://travisdowns.github.io/blog/2019/11/19/toupper.html

I usually order `#include`s intentionally (most specific to most general) in order to catch headers that lack explicitly `#include`ing of their own required headers.

**Comment by brettviren** [comment]
Setting `ColumnLimit:` to a finite value seems to fix the issue with only indenting the first line in a multi-line comment.

Unfortunately, then with `ReflowComments:true` it will make a hash of some comments with intentional formatting, in particular any using some kind of list format that clang-format doesn't already know.

If `ReflowComments:false` then we are back to the original problem.  But, with a generous `ColumnLimit` I think most comments will be handled correctly.  We can then manually fix up any comments that get butchered so clang-format treats them well from then on.

So, I suggest:
```
ColumnLimit: 120
ReflowComments:  true
```

**Comment by HaiwangYu** [comment]
Thanks @brettviren , with these change, some comments are formatted correctly like this:
https://github.com/HaiwangYu/wire-cell-toolkit/blob/clang-format/aux/inc/WireCellAux/TaggedFrameTensorSet.h

Some are not, like this:
https://github.com/HaiwangYu/wire-cell-toolkit/blob/clang-format/aux/inc/WireCellAux/TaggedFrameTensorSet.h


`BreakBeforeBraces: Allman` -> `BreakBeforeBraces: Stroustrup` according to @czczc 's suggestion.
Ref [this](https://stackoverflow.com/questions/29477654/how-to-make-clang-format-add-new-line-before-opening-brace-of-a-function)
Example for this:
https://github.com/HaiwangYu/wire-cell-toolkit/blob/clang-format/util/src/Array.cxx

**Comment by brettviren** [comment]
Hmm, I just tried the `SimpleTensor.h` example locally and it looks okay.    I just recopied your `.clang-format` from your github to make sure we are sync'ed.   Maybe you have an unpushed modification locally?

**Comment by HaiwangYu** [comment]
Yes, I did `clang-format` with a previous local branch, not the master of wirecell.
It seems for this type of comment, `clang-format` only format lines start with '*' other than the first line.

This means with current settings, some comments are not guaranteed to be formatted as expected. Given their initial format could be off.

**Comment by brettviren** [comment]
I don't know why I made this a separate issue. I'll close it.  Consider it merged with #74.
